# Generated by Django 4.1.4 on 2022-12-31 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_data', models.DateField(auto_now=True)),
                ('visitor_type', models.CharField(max_length=1)),
                ('identification_type', models.CharField(max_length=2)),
                ('identification', models.CharField(max_length=15, unique=True)),
                ('fullname', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=6)),
                ('entry', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
    ]
